name: TecoGAN
channels: 
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - pyyaml
  - lmdb
  - pytorch==1.8.0+cudatoolkit==10.2.0
  - torchvision==0.9.0
  - torchaudio==0.8.0
  - pip
  - pip:
    - opencv-python