name: TecoGAN
channels: 
  - pytorch
  - conda-forge
  - default
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - opencv-python
  - pyyaml
  - lmdb
  - torch==1.8.0
  - torchvision==0.9.0
  - torchaudio==0.8.0
  - cudatoolkit==10.2