# basic configs
scale: 1
manual_seed: 0
verbose: true
experiment: '003'

# dataset configs
dataset:
  degradation:
    type: Multimodal

  train:
    name: Multimodal
    data_path:  /disk/sdb1/avatars/dataset_EPE_data1/train # ./data/Multimodal/train #
    domain: real

    modalities: 
      ground_truth:
        name: frames
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_1:
        name: style_kmeans4
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_2:
        name: normal_renders
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_3:
        name: blur_box1
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_4:
        name: background
        type: standard
        mask:
          name: segments
          ext:
            - jpg
            - jpeg
            - png
    
    gt_crop_size: 192
    batch_size: 1
    num_workers: 1
    pin_memory: true
    decode: true

  validate1:
    name: Multimodal
    data_path: /disk/sdb1/avatars/dataset_EPE_data1/val #  ./data/Multimodal/val
    domain: real
    framewise: true
    
    modalities: 
      ground_truth:
        name: frames
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_1:
        name: style_kmeans4
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_2:
        name: normal_renders
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_3:
        name: blur_box1
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_4:
        name: background
        type: standard
        mask:
          name: segments
          ext:
            - jpg
            - jpeg
            - png

    num_workers: 1
    pin_memory: true
    decode: true

  validate2:
    name: Multimodal
    data_path: /disk/sdb1/avatars/dataset_EPE_data1/val # ./data/Multimodal/val 
    domain: virtual
    framewise: true
    
    modalities: 
      ground_truth:
        name: frames
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_1:
        name: style_kmeans4
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_2:
        name: normal_renders
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_3:
        name: blur_box1
        type: standard
        ext:
          - jpg
          - jpeg
          - png
      input_4:
        name: background
        type: standard
        mask:
          name: segments
          ext:
            - jpg
            - jpeg
            - png
    
    num_workers: 1
    pin_memory: true
    decode: true
  


# model configs
model:
  name: TecoGAN

  generator:
    name: FRNet  # frame-recurrent network
    in_nc: 12
    out_nc: 3
    nf: 64
    nb: 10
    load_path: ~ # pretrained_models/Multimodal/001/G_iter10000.pth


  discriminator:
    name: STNet  # spatio-temporal network
    orig_nc: 12
    in_nc: 3
    tempo_range: 3
    load_path: ~ # pretrained_models/Multimodal/001/D_iter10000.pth


# training configs
train:
  tempo_extent: 10

  start_iter: 0
  total_iter: 500000

  # configs for generator
  generator:
    lr: !!float 5e-5
    lr_schedule:
      type: FixedLR
    beta1: 0.9
    beta2: 0.999

  # configs for discriminator
  discriminator:
    update_policy: adaptive
    update_threshold: 0.4
    crop_border_ratio: 0.75
    lr: !!float 5e-5
    lr_schedule:
      type: FixedLR
    beta1: 0.9
    beta2: 0.999

  # other configs
  moving_first_frame: false
  moving_factor: 0.7

  # criterions
  pixel_crit:
    type: CB
    weight: 1
    reduction: mean

  warping_crit:
    type: CB
    weight: 1
    reduction: mean

  feature_crit:
    type: CosineSimilarity
    weight: 0.2
    reduction: mean
    feature_layers: [8, 17, 26, 35]

  pingpong_crit:
    type: CB
    weight: 0.5
    reduction: mean

  gan_crit:
    type: GAN
    weight: 0.01
    reduction: mean


# validation configs
test:
  test_freq: 10000

  # whether to save the generated SR results
  save_res: true
  res_dir: results   # use default dir

  # whether to save the test results in a json file
  save_json: false
  json_dir: ~  # use default dir

  padding_mode: reflect
  num_pad_front: 5


# metric configs
metric:
  PSNR:
    colorspace: y
    mult: 1.0

  LPIPS:
    model: net-lin
    net: alex
    colorspace: rgb
    spatial: false
    version: 0.1
    mult: 1.0

  tOF:
    mult: 1.0


# logger configs
logger:
  log_freq: 5000
  decay: 0.99
  ckpt_freq: 5000
