# basic configs
scale: 4
manual_seed: 0
# dataset configs
dataset:
  degradation:
    type: BI

  common:
    name: Actors
    filter_file: ~
    data_type: rgb
    crop_size: 128
    batch_size: 1
    num_workers: 1
    pin_memory: true
