# basic configs
scale: 1
manual_seed: 0
# dataset configs
dataset:
  degradation:
    type: Style

  common:
    name: ActorsVox
    filter_file: ~
    data_type: rgb
    crop_size: 128
    batch_size: 1
    num_workers: 4
    pin_memory: true

device: cuda
