# basic configs
scale: 1
manual_seed: 0
verbose: true
experiment: '004'

# dataset configs
dataset:
  degradation:
    type: Style

  train:
    name: Actors
    gt_seq_dir: data/Actors/train/real.lmdb
    lr_seq_dir: data/Actors/train/real_Style.lmdb
    filter_file: ~
    data_type: rgb
    gt_crop_size: 128
    batch_size: 2
    num_workers: 2
    pin_memory: true
    decode: true

  validate_Melina_Real:
    name: Actors
    actor_name: MelinaJuergens
    domain: real
    filter_file: ~
    num_workers: 1
    pin_memory: true
  
  # validate_Melina_Virtual:
  #   name: Actors
  #   actor_name: MelinaJuergens
  #   domain: virtual
  #   filter_file: ~
  #   num_workers: 1
  #   pin_memory: true

  validate_Norman_Real:
    name: Actors
    actor_name: NormanReedus
    domain: real
    filter_file: ~
    num_workers: 1
    pin_memory: true
  
  validate_Norman_Virtual:
    name: Actors
    actor_name: NormanReedus
    domain: virtual
    filter_file: ~
    num_workers: 1
    pin_memory: true

  validate_Mads_Real:
    name: Actors
    actor_name: MadsMikkelsen
    domain: real
    filter_file: ~
    num_workers: 1
    pin_memory: true
  
  validate_Mads_Virtual:
    name: Actors
    actor_name: MadsMikkelsen
    domain: virtual
    filter_file: ~
    num_workers: 1
    pin_memory: true

  validate_Madeleine_Real:
    name: Actors
    actor_name: MadeleineKnight
    domain: real
    filter_file: ~
    num_workers: 1
    pin_memory: true
  
  validate_Madeleine_Virtual:
    name: Actors
    actor_name: MadeleineKnight
    domain: virtual
    filter_file: ~
    num_workers: 1
    pin_memory: true

  validate_Lea_Real:
    name: Actors
    actor_name: LeaSeydoux
    domain: real
    filter_file: ~
    num_workers: 1
    pin_memory: true
  
  validate_Lea_Virtual:
    name: Actors
    actor_name: LeaSeydoux
    domain: virtual
    filter_file: ~
    num_workers: 1
    pin_memory: true

  validate_Other_Real:
    name: Actors
    actor_name: Other
    domain: real
    filter_file: ~
    num_workers: 1
    pin_memory: true
  
  validate_Other_Virtual:
    name: Actors
    actor_name: Other
    domain: virtual
    filter_file: ~
    num_workers: 1
    pin_memory: true


# model configs
model:
  name: TecoGAN

  generator:
    name: FRNet  # frame-recurrent network
    in_nc: 3
    out_nc: 3
    nf: 64
    nb: 10
    load_path: pretrained_models/Style/004/G_iter20000.pth

  discriminator:
    name: STNet  # spatio-temporal network
    in_nc: 3
    tempo_range: 3
    load_path: pretrained_models/Style/004/D_iter20000.pth


# training configs
train:
  tempo_extent: 10

  start_iter: 19998
  total_iter: 500000

  # configs for generator
  generator:
    lr: !!float 5e-5
    lr_schedule:
      type: FixedLR
    beta1: 0.9
    beta2: 0.999

  # configs for discriminator
  discriminator:
    update_policy: adaptive
    update_threshold: 0.4
    crop_border_ratio: 0.75
    lr: !!float 5e-5
    lr_schedule:
      type: FixedLR
    beta1: 0.9
    beta2: 0.999

  # other configs
  moving_first_frame: false
  moving_factor: 0.7

  # criterions
  pixel_crit:
    type: CB
    weight: 1
    reduction: mean

  warping_crit:
    type: CB
    weight: 1
    reduction: mean

  feature_crit:
    type: CosineSimilarity
    weight: 0.2
    reduction: mean
    feature_layers: [8, 17, 26, 35]

  pingpong_crit:
    type: CB
    weight: 0.5
    reduction: mean

  gan_crit:
    type: GAN
    weight: 0.01
    reduction: mean


# validation configs
test:
  test_freq: 20000

  # whether to save the generated SR results
  save_res: true
  res_dir: results   # use default dir

  # whether to save the test results in a json file
  save_json: false
  json_dir: ~  # use default dir

  padding_mode: reflect
  num_pad_front: 5


# metric configs
metric:
  PSNR:
    colorspace: y
    mult: 1.0

  LPIPS:
    model: net-lin
    net: alex
    colorspace: rgb
    spatial: false
    version: 0.1
    mult: 1.0

  tOF:
    mult: 1.0


# logger configs
logger:
  log_freq: 5000
  decay: 0.99
  ckpt_freq: 5000

